#ifndef TUNETUBE_CONFIG_H
#define TUNETUBE_CONFIG_H

#define TUNETUBE_VERSION @"v1.0.2-stable"
#define TUNETUBE_API_KEY_DEFAULTS_KEY @"YTMAPIKey"
#define TUNETUBE_LIBRARY_DEFAULTS_KEY @"TuneTubeFavorites"
#define TUNETUBE_HISTORY_DEFAULTS_KEY @"TuneTubeRecentTracks"
#define TUNETUBE_BACKGROUND_AUDIO_DEFAULTS_KEY @"TuneTubeBackgroundAudio"
#define TUNETUBE_LIGHT_THEME_DEFAULTS_KEY @"TuneTubeLightTheme"
#define TUNETUBE_BACKGROUND_AUDIO_DID_CHANGE_NOTIFICATION @"TuneTubeBackgroundAudioDidChangeNotification"

#endif /* TUNETUBE_CONFIG_H */
